---

## Install
- name: Apache2 | Install Apache
  apt: name=apache2-mpm-{{ apache_mpm_worker }} state=latest

- shell: apache2 -v | head -n1 | sed 's/.*Apache\/\(.*\)\s.*/\1/'
  register: apache_version

## Install modules
- name: Apache2 | Install Apache modules
  apt: name={{ item }} state=latest
  with_items: apache_install_modules
  when: apache_install_modules is defined

## Enable modules
- name: Apache2 | Enable modules
  command: a2enmod {{ item }} #creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items: apache_enable_modules
  when: apache_enable_modules is defined
  notify: restart apache2

## Disable modules
- name: Apache2 | Disable modules
  command: a2dismod {{ item }}
  with_items: apache_disable_modules
  when: apache_disable_modules is defined
  notify: restart apache2

## vhosts einrichten
- include: setup_vhosts.yml

## Check service
- name: Apache2 | Check service daemon
  service: name=apache2 state=started
