---
dependencies: []

galaxy_info:
  author: David 'debauer' Bauer
  description: Apache 2.x Debian
  company: "Kalt! Medien UG"
  license: ""
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  categories:
    - web
